seed: 42
batch_size: 16
epochs: 4
lr: 2.5e-4
warmup_steps: 2000
weight_decay: 0.01
mixed_precision: true
clip_norm: 1.0

loss:
  ce_weight: 1.0
  coverage_weight: 0.0
  length_reg_weight: 0.05

augment:
  randflip: true
